### ISSUE TITLE
Auth Issues

### ISSUE THREAD

**Issue by madoobus** [carboncoop/tesla-gateway-ha-component#2]
Hi guys,
I am (admittedly) a noob to HomeAssistant, and followed the implementation instructions to the letter.  The manual Call is failing, and I am getting the following Auth error:

2021-03-13 13:31:16 DEBUG (MainThread) [custom_components.tesla_gateway] Step 1: GET https://auth.tesla.com/oauth2/v3/authorize
params (('client_id', 'ownerapi'), ('code_challenge', '<MANUALLY DELETED STRING HERE IN CASE IT SHOWS SECURITY DETAILS>'), ('code_challenge_method', 'S256'), ('redirect_uri', 'https://auth.tesla.com/void/callback'), ('response_type', 'code'), ('scope', 'openid email offline_access'), ('state', '<MANUALLY DELETED STRING HERE IN CASE IT SHOWS SECURITY DETAILS>'))

Here is the manual Call I made:
service: tesla_gateway.set_operation
data:
  real_mode: backup
  backup_reserve_percent: 10

Is anyone familiar with this issue - and able to provide simple to follow instructions as to how to remediate pls?

**Comment by peteretep** [comment]
Hi - you may have more luck getting help on this thread - https://community.home-assistant.io/t/add-support-for-tesla-powerwall/142280/72
The person who originally wrote this code is active there.

**Comment by madoobus** [comment]
@peteretep thank you, will do.
