### ISSUE TITLE
Access Denied Error

### ISSUE THREAD

**Issue by benschwartz42** [carboncoop/tesla-gateway-ha-component#3]
I an getting an Access Denied error. Was working great for awhile. Now stopped working. 

Logger: homeassistant.core
Source: custom_components/tesla_gateway/__init__.py:130
First occurred: April 19, 2021, 12:00:24 AM (9 occurrences)
Last logged: 4:24:33 PM

Error executing service: <ServiceCall tesla_gateway.set_reserve (c:7e50a77bcddc2def15512fef8052b5f8): reserve_percent=60>
Error executing service: <ServiceCall tesla_gateway.set_reserve (c:2b4cd1ece81ecbd922213775d644de5f): reserve_percent=50>
Error executing service: <ServiceCall tesla_gateway.set_reserve (c:2781b0d514205d16854b03dc65337ce6): reserve_percent=50>
Error executing service: <ServiceCall tesla_gateway.set_reserve (c:17b7194723cc118ade1c9c50c775312c): reserve_percent=50>
Error executing service: <ServiceCall tesla_gateway.set_reserve (c:42f61b49f996ee54bd7e6114a864bca0): reserve_percent=50>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1496, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/tesla_gateway/__init__.py", line 463, in async_set_reserve
    owner_token = yield from get_owner_api_token()
  File "/config/custom_components/tesla_gateway/__init__.py", line 406, in get_owner_api_token
    access_token = yield from SSO_login()
  File "/config/custom_components/tesla_gateway/__init__.py", line 130, in SSO_login
    raise ValueError(
ValueError: ('Step 1: failed after %d attempts, last response %s:\n%s', 7, 403, '<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;authorize&#63;" on this server.<P>\nReference&#32;&#35;18&#46;a7fa3b17&#46;1618804821&#46;27fcb2a6\n</BODY>\n</HTML>\n')

**Comment by benschwartz42** [comment]
Logger: custom_components.tesla_gateway
Source: custom_components/tesla_gateway/__init__.py:121
Integration: Tesla Gateway (documentation, issues)
First occurred: April 19, 2021, 12:00:01 AM (63 occurrences)
Last logged: 4:24:30 PM

Step 1: Error 403 on attempt 2, call https://auth.tesla.com/oauth2/v3/authorize?client_id=ownerapi&code_challenge=wDDSnslE3fLv5n7P14P1r-PKCjKvL_sjvWCUQ2-elUA&code_challenge_method=S256&redirect_uri=https://auth.tesla.com/void/callback&response_type=code&scope=openid+email+offline_access&state=HaMYgAIoI9exFNDiZdPo3g: <HTML><HEAD> <TITLE>Access Denied</TITLE> </HEAD><BODY> <H1>Access Denied</H1> You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;authorize&#63;" on this server.<P> Reference&#32;&#35;18&#46;a7fa3b17&#46;1619036657&#46;409beff0 </BODY> </HTML>
Step 1: Error 403 on attempt 3, call https://auth.tesla.com/oauth2/v3/authorize?client_id=ownerapi&code_challenge=wDDSnslE3fLv5n7P14P1r-PKCjKvL_sjvWCUQ2-elUA&code_challenge_method=S256&redirect_uri=https://auth.tesla.com/void/callback&response_type=code&scope=openid+email+offline_access&state=HaMYgAIoI9exFNDiZdPo3g: <HTML><HEAD> <TITLE>Access Denied</TITLE> </HEAD><BODY> <H1>Access Denied</H1> You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;authorize&#63;" on this server.<P> Reference&#32;&#35;18&#46;a7fa3b17&#46;1619036660&#46;409c04a3 </BODY> </HTML>
Step 1: Error 403 on attempt 4, call https://auth.tesla.com/oauth2/v3/authorize?client_id=ownerapi&code_challenge=wDDSnslE3fLv5n7P14P1r-PKCjKvL_sjvWCUQ2-elUA&code_challenge_method=S256&redirect_uri=https://auth.tesla.com/void/callback&response_type=code&scope=openid+email+offline_access&state=HaMYgAIoI9exFNDiZdPo3g: <HTML><HEAD> <TITLE>Access Denied</TITLE> </HEAD><BODY> <H1>Access Denied</H1> You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;authorize&#63;" on this server.<P> Reference&#32;&#35;18&#46;a7fa3b17&#46;1619036664&#46;409c18a7 </BODY> </HTML>
Step 1: Error 403 on attempt 5, call https://auth.tesla.com/oauth2/v3/authorize?client_id=ownerapi&code_challenge=wDDSnslE3fLv5n7P14P1r-PKCjKvL_sjvWCUQ2-elUA&code_challenge_method=S256&redirect_uri=https://auth.tesla.com/void/callback&response_type=code&scope=openid+email+offline_access&state=HaMYgAIoI9exFNDiZdPo3g: <HTML><HEAD> <TITLE>Access Denied</TITLE> </HEAD><BODY> <H1>Access Denied</H1> You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;authorize&#63;" on this server.<P> Reference&#32;&#35;18&#46;8dfa3b17&#46;1619036667&#46;3a6ce82c </BODY> </HTML>
Step 1: Error 403 on attempt 6, call https://auth.tesla.com/oauth2/v3/authorize?client_id=ownerapi&code_challenge=wDDSnslE3fLv5n7P14P1r-PKCjKvL_sjvWCUQ2-elUA&code_challenge_method=S256&redirect_uri=https://auth.tesla.com/void/callback&response_type=code&scope=openid+email+offline_access&state=HaMYgAIoI9exFNDiZdPo3g: <HTML><HEAD> <TITLE>Access Denied</TITLE> </HEAD><BODY> <H1>Access Denied</H1> You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;authorize&#63;" on this server.<P> Reference&#32;&#35;18&#46;a7fa3b17&#46;1619036670&#46;409c4c2e </BODY> </HTML>

**Comment by HeraldCoupe** [comment]
Same issue here, sadly.

**Comment by sandyman44** [comment]
exact same error for me. not used this integration for a month or so - just updated to latest version and tried to use it again.
looking at the tesla phone app it seems to have changed (they added a new section in Powerwall called "Vehicle Charging During Power Outage") so probably their API has been changed.
